---
version: '3.1'

services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
