# -*- mode: ruby -*-
# vi: set ft=ruby :

if Vagrant::Util::Platform.wsl?
  unless Vagrant.has_plugin?("virtualbox_WSL2")
    raise 'virtualbox_WSL2 is not installed, install with "vagrant plugin install virtualbox_WSL2"'
  end
end

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General VM configuration.
  config.vm.box = "geerlingguy/debian11"
  config.ssh.insert_key = false

  # Sync configuration.
  if Vagrant::Util::Platform.wsl?
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end

  # Virtualbox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.name = "postgis"
    v.cpus = 1
    v.memory = 2048
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Ansible provisioner.
  # config.vm.provision "ansible" do |ansible|
  #   ansible.compatibility_mode = "2.0"
  #   ansible.playbook = "provisioning/main.yml"
  #   ansible.become = true
  # end
end
